Repository AY2122S1-CS2113T-F14-3/tp, pull requests merged in 2021-11, with the labels that each got.

#236 Teoziyiivy Javadoc
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/WeightTracker.java
  src/main/java/seedu/duke/WeightTrackerMessages.java
  src/test/java/seedu/duke/WeightTrackerTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task, type.Bug, type.JUnit

#237 Jiewen final countdown
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/arvejw.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/WorkoutTracker.java
  src/main/java/seedu/duke/schedule/ScheduleTracker.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
  src/main/java/seedu/duke/schedule/WorkoutActivity.java
Labels: priority.Medium

#238 Fix checkstyle
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
Labels: priority.Medium

#241 Edward zy wang v2
  docs/UserGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
Labels: priority.High, type.Bug

#242 add ppp
  docs/team/EdwardZYWang.md
Labels: type.Task

#243 Vishal jeyaram v2.1
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/vishaljeyaram.md
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/WeightTracker.java
  src/main/java/seedu/duke/exceptions/foodbank/InvalidFluidIndexException.java
  src/main/java/seedu/duke/exceptions/foodbank/InvalidMealIndexException.java
  src/main/java/seedu/duke/exceptions/weight/FutureWeightException.java
Labels: type.Bug

#248 Bug fixes
  docs/UserGuide.md
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/exceptions/fluid/noVolumeEntered.java
  src/main/java/seedu/duke/exceptions/foodbank/DuplicateFood.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
Labels: type.Bug

#249 PPP pragyan01
  docs/team/pragyan01.md
Labels: type.Enhancement, severity.Medium

#250 Gradle fixes
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/exceptions/fluid/NoVolumeEntered.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
Labels: type.Enhancement, type.Bug

#252 Add PPP for ivy
  docs/team/teoziyiivy.md
Labels: type.Enhancement, severity.Medium

#253 Java docs
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Tracker.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/fluid/DeleteEmptyFluidListException.java
  src/main/java/seedu/duke/exceptions/fluid/FluidExceptions.java
  src/main/java/seedu/duke/exceptions/fluid/InvalidFluidDescription.java
  src/main/java/seedu/duke/exceptions/fluid/NoDeleteFluidIndexException.java
  src/main/java/seedu/duke/exceptions/fluid/NoFluidToDelete.java
  src/main/java/seedu/duke/exceptions/fluid/NoVolumeEntered.java
Labels: priority.Medium, type.Enhancement

#255 Java docs and code claim
  src/main/java/seedu/duke/Calculator.java
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Tracker.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/LoadException.java
  src/main/java/seedu/duke/exceptions/fluid/DeleteEmptyFluidListException.java
  src/main/java/seedu/duke/exceptions/fluid/FluidExceptions.java
  src/main/java/seedu/duke/exceptions/fluid/InvalidFluidDescription.java
  src/main/java/seedu/duke/exceptions/fluid/NoDeleteFluidIndexException.java
  src/main/java/seedu/duke/exceptions/fluid/NoFluidToDelete.java
  src/main/java/seedu/duke/exceptions/fluid/NoVolumeEntered.java
  src/main/java/seedu/duke/exceptions/foodbank/DuplicateFood.java
  src/main/java/seedu/duke/exceptions/foodbank/EmptyFluidBankException.java
  src/main/java/seedu/duke/exceptions/foodbank/EmptyFoodDescription.java
  src/main/java/seedu/duke/exceptions/foodbank/EmptyMealBankException.java
  src/main/java/seedu/duke/exceptions/foodbank/FoodBankException.java
Labels: priority.Medium, type.Enhancement, type.JUnit

#256 Add new schedule exceptions
  docs/UserGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/schedule/DuplicateRescheduledWorkoutException.java
  src/main/java/seedu/duke/exceptions/schedule/MissingActivityQuantifierException.java
  src/main/java/seedu/duke/exceptions/schedule/MissingActivitySplitterException.java
  src/main/java/seedu/duke/exceptions/schedule/UnnecessaryQuantifierException.java
  src/main/java/seedu/duke/schedule/ScheduleTracker.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
Labels: priority.Medium

#257 Edward zy wang v2
  docs/team/EdwardZYWang.md
  docs/team/edwardzywang.md
  src/main/java/seedu/duke/Calculator.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserHelp.java
Labels: priority.High

#258 add junits
  src/test/java/seedu/duke/CommandManagerTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: priority.High, type.JUnit

#261 Fluid Junit and DG update
  diagrams/Fluid_DeleteFluid_Sequence.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/exceptions/fluid/EmptyFluidList.java
  src/test/java/seedu/duke/FluidTest.java
Labels: type.Enhancement, severity.Medium, type.JUnit

#262 Vishal jeyaram v2.1
  diagrams/Meal_ListMeals_sequence.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Keywords.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/fluid/NegativeVolumeException.java
  src/main/java/seedu/duke/exceptions/foodbank/InvalidFluidIndexException.java
  src/main/java/seedu/duke/exceptions/foodbank/InvalidMealIndexException.java
  src/main/java/seedu/duke/exceptions/foodbank/NegativeCaloriesException.java
  src/main/java/seedu/duke/exceptions/foodbank/NoFoodFoundException.java
  src/main/java/seedu/duke/exceptions/foodbank/NoFoodIndexException.java
  src/main/java/seedu/duke/exceptions/meal/EmptyMealListException.java
  src/main/java/seedu/duke/exceptions/meal/MealException.java
  src/main/java/seedu/duke/exceptions/meal/NoDeleteMealIndexException.java
  src/main/java/seedu/duke/exceptions/meal/NoMealDescriptionException.java
  src/main/java/seedu/duke/exceptions/meal/NoMealDetailsException.java
  src/main/java/seedu/duke/exceptions/meal/NoSuchMealIndexException.java
  src/test/java/seedu/duke/MealTest.java
Labels: priority.High, type.Enhancement

#263 Java doc
  src/main/java/seedu/duke/Ui.java
Labels: priority.Medium, type.Enhancement

#264 removed dead code for fluid class
  src/main/java/seedu/duke/Fluid.java
Labels: priority.Low, type.Enhancement

#265 Code claim
  docs/UserGuide.md
  src/main/java/seedu/duke/Calculator.java
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/WeightTracker.java
  src/main/java/seedu/duke/WeightTrackerMessages.java
Labels: priority.Low, type.Enhancement

#268 Split UG share
  docs/UserGuide.md
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
Labels: priority.Medium

#269 Vishal jeyaram v2.1
  docs/UserGuide.md
Labels: priority.Medium

#273 UG
  docs/UserGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/FluidTest.java
Labels: priority.Medium, type.Enhancement

#275 UG and DG tweaks
  diagrams/ScheduleTracker_add_sequence.puml
  diagrams/ScheduleTracker_add_sequence_ref.puml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/schedule/ScheduleTracker.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
  src/main/java/seedu/duke/schedule/WorkoutActivity.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/schedule/ScheduleTrackerTest.java
  src/test/java/seedu/duke/schedule/WorkoutTrackerTest.java
Labels: priority.High

#276 DG sequence diagram added
  diagrams/Fluid_GetCalories.puml
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Enhancement

#278 DG+JUnit for foodbank and fluid classes
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
  src/test/java/seedu/duke/FluidTest.java
  src/test/java/seedu/duke/FoodBankTest.java
Labels: priority.Medium, type.Enhancement

#281 JUnit fixes for Foodbank & Fluid
  src/test/java/seedu/duke/FluidTest.java
  src/test/java/seedu/duke/FoodBankTest.java
Labels: priority.Medium, type.Enhancement

#282 DG for fluid class and code fixes
  docs/DeveloperGuide.md
  src/test/java/seedu/duke/FluidTest.java
Labels: priority.Low, type.Enhancement

#283 Teoziyiivy ppp
  diagrams/WeightTracker_add_sequence.puml
  diagrams/WeightTracker_class.puml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/teoziyiivy.md
  src/main/java/seedu/duke/Calculator.java
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/WeightTracker.java
  src/test/java/seedu/duke/FluidTest.java
  src/test/java/seedu/duke/WeightTrackerTest.java
Labels: priority.Medium, type.Task, type.Bug, severity.Low, type.JUnit

#284 Zikun fixes
  src/main/java/seedu/duke/WeightTracker.java
Labels: priority.Medium, type.Task, severity.Low

#286 Teoziyiivy PPP Edits
  docs/DeveloperGuide.md
  docs/team/teoziyiivy.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.High, type.Task, severity.Low

#294 Edward zy wang v2
  docs/DeveloperGuide.md
  docs/team/edwardzywang.md
Labels: priority.High

#296 Teoziyiivy final edits
  docs/DeveloperGuide.md
  src/test/java/seedu/duke/WeightTrackerTest.java
Labels: priority.Medium, type.Task, severity.Low, type.JUnit

#298 Vishal jeyaram v2.1
  docs/team/vishaljeyaram.md
Labels: type.Task

#305 Teoziyiivy additional edits
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/teoziyiivy.md
Labels: priority.High, type.Task, type.Bug, severity.Low

#306 Fix formatting
  docs/DeveloperGuide.md
Labels: priority.High, type.Bug, severity.Low

#307 Add page break for PPP
  docs/team/teoziyiivy.md
Labels: priority.Medium, type.Bug, severity.Low

#308 DG updates + Fluid bug fixes
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/exceptions/foodbank/EmptyFoodDescription.java
  src/main/java/seedu/duke/exceptions/foodbank/EmptyLibraryDescription.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
Labels: priority.Medium, type.Enhancement

#310 Vishal jeyaram v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/pragyan01.md
  docs/team/vishaljeyaram.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UserHelp.java
Labels: priority.High

#313 Fix text wrapping DG
  docs/DeveloperGuide.md
Labels: priority.High

#314 Fix text wrapping
  docs/DeveloperGuide.md
Labels: priority.High

#315 Update readme
  docs/README.md
Labels: priority.High
