Repository AY2122S1-CS2113T-F14-3/tp, pull requests merged in 2021-10, with the labels that each got.

#55 Ui, Keywords, Junits, Help command
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Keywords.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserHelp.java
  src/test/java/seedu/duke/UserHelpTest.java
Labels: priority.High, type.Story, type.Task, type.JUnit

#65 fluid-add, delete, list
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/UserHelp.java
Labels: priority.High, type.Story

#78 Jiewen final touchesv1.0
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.Medium

#84 Jiewen final touchesv1.0
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/gym/ScheduleTracker.java
  src/main/java/seedu/duke/gym/WorkoutTracker.java
Labels: priority.High, type.Bug

#89 Edit UserGuide
  docs/UserGuide.md
Labels: priority.Medium

#91 Add UG
  docs/UserGuide.md
Labels: priority.Medium

#98 Enhancements to scheduletracker
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/gym/ScheduleTracker.java
  src/main/java/seedu/duke/gym/ScheduledWorkout.java
  src/main/java/seedu/duke/gym/WorkoutTracker.java
  src/test/java/seedu/duke/gym/ScheduleTrackerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, type.Enhancement

#100 Add more JUnit for Fluid, gradle fixes
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/Fluid.java
  src/test/java/seedu/duke/FluidTest.java
  src/test/java/seedu/duke/UserHelpTest.java
Labels: priority.High, type.JUnit

#101 add method to store date and time if left blank
  docs/UserGuide.md
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Fluid.java
  src/main/java/seedu/duke/Keywords.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.High, type.Story, type.Enhancement

#102 Vishal jeyaram v2.0
  src/main/java/seedu/duke/Calculator.java
Labels: priority.Medium, type.Story

#104 edit UI to skip calculator if needed. fixed bugs
  src/main/java/seedu/duke/Calculator.java
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/Ui.java
Labels: priority.Medium, type.Enhancement

#107 Vishal jeyaram v2.0
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Keywords.java
  src/main/java/seedu/duke/Meal.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/exceptions/FoodBankException.java
Labels: priority.High, type.Enhancement

#109 Foodbank-code fixes
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/FoodBank.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.High, type.Enhancement

#114 Vishal jeyaram v2.0
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Duke.java
  userData.txt
Labels: priority.High, type.Story

#115 edit UG
  docs/UserGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/test/java/seedu/duke/FluidTest.java
Labels: priority.High, type.Task

#125 Add storing and loading for workout and schedule
  Food.txt
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/DateTracker.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/gym/ScheduleTracker.java
  src/main/java/seedu/duke/gym/WorkoutTracker.java
  src/test/java/seedu/duke/gym/ScheduleTrackerTest.java
  src/test/java/seedu/duke/gym/WorkoutTrackerTest.java
  userData.txt
Labels: priority.High

#130 Add WeightTracker Developer Guide
  diagrams/WeightTracker_add_sequence.puml
  diagrams/WeightTracker_check_sequence.puml
  diagrams/WeightTracker_class.puml
  diagrams/WeightTracker_delete_sequence.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/WeightTracker.java
  src/main/java/seedu/duke/WeightTrackerMessages.java
Labels: priority.Medium, type.Task

#137 list caloris & volume, code fixes
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
Labels: priority.High, type.Story

#141 edit UG
  docs/DeveloperGuide.md
Labels: priority.Medium

#232 Fix some PED bugs for schedule
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/WorkoutTracker.java
  src/main/java/seedu/duke/exceptions/schedule/DuplicateScheduledWorkoutException.java
  src/main/java/seedu/duke/exceptions/schedule/InvalidActivityFormatException.java
  src/main/java/seedu/duke/exceptions/workout/DuplicateWorkoutException.java
  src/main/java/seedu/duke/schedule/ScheduleTracker.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/schedule/ScheduleTrackerTest.java
  src/test/java/seedu/duke/schedule/WorkoutTrackerTest.java
Labels: priority.High, type.Bug

#234 Add JavaDoc and minor logic tweaks
  docs/UserGuide.md
  src/main/java/seedu/duke/ClickfitMessages.java
  src/main/java/seedu/duke/CommandManager.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/WorkoutTracker.java
  src/main/java/seedu/duke/exceptions/schedule/MissingScheduleSeparatorException.java
  src/main/java/seedu/duke/exceptions/workout/MissingWorkoutCalorieSeparatorException.java
  src/main/java/seedu/duke/schedule/ScheduleTracker.java
  src/main/java/seedu/duke/schedule/ScheduledWorkout.java
  src/main/java/seedu/duke/schedule/WorkoutActivity.java
Labels: priority.High
